### ISSUE TITLE
Implement custom css located in plugin to theme

### ISSUE THREAD

**Issue by arnorb** [piratar/piratar.is#100]
A css override was put into a plugin on the server but the CSS should all be in the theme.

This is the CSS:

```
.tribe-events-event-meta.secondary {
	position: static;
}

.post blockquote {
	color: #2e2e2e;
}
```

It then needs to be removed from the plugin, located at Útlit->Edit CSS.

**Comment by baldurjonsson** [comment]
Bætti við smá viðbót, til þess að það sé auðveldara að lesa fundargerðir í mobile.

```
@media (max-width:991px) {
	.alpha {
		width: 100%;
	}
}
```
