### ISSUE TITLE
Snurfusa og gefa út pólskar síður 

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#104]
Til KG og svo forritara
Í veftrénu er síða með pólsku innihaldi - það þarf að snurfusa efnið til m.t.t. readability og setja inn myndir, spurning hvort þetta á heima á einni síðu eða mörgum, efnið getur bæði verið ein eða sem móðursíða og börn - hvort heldur sem kemur betur út.
piratar.is/polski/
Svo þegar síðan lúkkar eðlilega þarf að gefa hana út og setja vísun í templeitið á PL á sama hátt og við vísum á EN.

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setja upp Pólskar síður](https://trello.com/c/Hw2np059/11-setja-upp-p%C3%B3lskar-s%C3%AD%C3%B0ur)

**Comment by stjanigunnars** [comment]
Sýnist þetta vera komið @thorlaug
