### ISSUE TITLE
Hanna fyrstu drög að útliti

### ISSUE THREAD

**Issue by maranomynet** [piratar/piratar.is#22]
Það má byrja á þessu áður en Style Guide er kominn í 100% endanlegt form.
Við vitum megin drætti Styleguidesins og getum byrjað mockup vinnuna a.m.k. – svo hægt sé að byrja vefnun.

**Comment by arnorb** [comment]
@andri varst þú eitthvað kominn af stað í þessu? ég get farið í þessa vinnu núna af einhverjum krafti.

**Comment by andri** [comment]
Hérna er sú hönnun sem ég var byrjaður að gera. Þetta er ekkert merkilegt, þú mátt nota þetta sem grunn eða bara henda þessu í ruslið og byrja uppá nú nýtt :) Þarna er ég að nota Source Sans.

![piratar-01](https://cloud.githubusercontent.com/assets/123914/12745930/eef2625e-c993-11e5-825b-0e7f09f0872a.png)

Sketch fæll.

[piratar-web-0.1.zip](https://github.com/piratar/piratar.is/files/113697/piratar-web-0.1.zip)

**Comment by andri** [comment]
@arnorb, pælingin hjá mér var að gera eitthvað sem væru sem næst flat en nota smá skugga fyrir valmyndir og slíkt. Kannski takka. Valmyndin væri þarna til hægri og alltaf visible nema á small desktop og niður.

**Comment by andri** [comment]
Svo er hérna pæling varðandi valmyndina. Hún myndi opnast nánast full-screen nema skilja eftir smá rönd þarna til vinstri til að loka.

![piratar-01-menu](https://cloud.githubusercontent.com/assets/123914/12746530/0918777e-c997-11e5-8cf9-f5eb9f4a464e.png)

**Comment by arnorb** [comment]
Takk fyrir þetta @andri , ég ætla að skoða þetta.
