### ISSUE TITLE
Integrate task builder like grunt or gulp for minifying javascript and css.

### ISSUE THREAD

**Issue by davidhalldor** [piratar/piratar.is#24]
Work in progress.

**Comment by maranomynet** [comment]
Having used both Grunt and Gulp, I strongly recommend not using Grunt. Its supposed simplicity very quickly results in annoying complexity and inflexibility.

**Comment by maranomynet** [comment]
BTW, Arnór and/or whoever will write the JavaScript and CSS will surely wish to handle minification, linting, transpiling, stylus-compilation, autoprefixing, and other tasks themselves anyway - so I'm uncertain if setting this up as a separate/standalone task makes as much sense as it might initially seem.
