### ISSUE TITLE
Viewport issue in mobile

### ISSUE THREAD

**Issue by busla** [piratar/piratar.is#27]
Device: iPhone 6+
Browser: Safari

![image1](https://cloud.githubusercontent.com/assets/3162968/17456634/ec440c1e-5bde-11e6-99b2-93ef9cdac150.PNG)

![image1](https://cloud.githubusercontent.com/assets/3162968/17456636/f3f8816a-5bde-11e6-804b-de876b31df8f.PNG)

**Comment by baldurjonsson** [comment]
Appears there's no media query for mobile dismissing the whitespace on news.

The css: `width: calc(100% - 360px);`
