### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by busla** [piratar/piratar.is#29]
http://piratar.is/kosningar/profkjor-althingiskosningar/profkjor-sudur/

![screen shot 2016-08-08 at 21 08 11](https://cloud.githubusercontent.com/assets/3162968/17492511/65b24740-5dac-11e6-9a34-f8d59b7dbaf0.png)

**Comment by busla** [comment]
Fann svo frambjóðendasíðuna annar staðar og hún virkaði.

Fór á þessa síðu héðan:
![screen shot 2016-08-08 at 21 13 32](https://cloud.githubusercontent.com/assets/3162968/17492698/3aecc098-5dad-11e6-8934-d0e30584232c.png)

Sem leiddi mig hingað:
![screen shot 2016-08-08 at 21 14 17](https://cloud.githubusercontent.com/assets/3162968/17492714/4bf33bec-5dad-11e6-9444-a62e8ed79234.png)

**Comment by hallakol** [comment]
This issue is now moot as the /kosningar website is changing to take on a different role. Structure along with all links in the megamenu are being updated.
