### ISSUE TITLE
Kosningavefur <> Aðalvefur

### ISSUE THREAD

**Issue by busla** [piratar/piratar.is#30]
Mér langar að koma með tillögu um að það sé gefin einhver ábending um að ég sé á kosningavefnum, hvort sem það sé annar litur í nav, annað layout í main eða eitthvað slíkt.

Ég átta mig ekki á því að ég sé á öðrum vef (með öðrum nav) því vefirnir eru að nota sömu templates.

**Comment by busla** [comment]
Setja "KOSNINGAVEFUR 2016" í header?

**Comment by busla** [comment]
Color inverse á allri síðunni jafnvel?

**Comment by hallakol** [comment]
Þurfum að fá inn fyrirsögn á bannerana á forsíðunni fyrir akkúrat þetta.

**Comment by andri** [comment]
Merge with: #55
