### ISSUE TITLE
Burger menu does not toggle

### ISSUE THREAD

**Issue by viktorsmari** [piratar/piratar.is#31]
Header overlays menu 
![screenshot_2016-08-12-21-21-57](https://cloud.githubusercontent.com/assets/1689020/17634477/1539a59a-60d3-11e6-97d3-44bc2d393f6a.png)

The menu has been moved down, but the toggling is still an issue

**Comment by viktorsmari** [comment]
The menu has been moved down, but the toggling is still an issue

**Comment by baldurjonsson** [comment]
The mobile menu should also hide when the viewport is expanded.
For example: Turning á highres tablet 90° or manually dragging a browser windows on a desktop.

![image](https://cloud.githubusercontent.com/assets/3398226/18445638/0dbd9062-790e-11e6-8b5e-d061291afdf4.png)

**Comment by andri** [comment]
Fixed indirectly.
