### ISSUE TITLE
Linkar sjást mjög illa.

### ISSUE THREAD

**Issue by viktorsmari** [piratar/piratar.is#35]
Þetta er auðvitað mismunandi eftir skjám en linkarnir okkar sjást mjög illa.

Ég er gamaldags og vil helst hafa undirstrik þar sem hægt er að smella á linka, amk sjáanlegan lit.
Er einhver hönnuður hérna sem hefur álit á þessu?

Það sést illa á þessari mynd en "Ungir Píratar" er t.d. linkur.

![img_20160823_191551](https://cloud.githubusercontent.com/assets/1689020/17902763/e93f25ca-6968-11e6-819c-a59916b85bf3.jpg)

Hérna er þetta með undirstriki:

![img_20160823_194411](https://cloud.githubusercontent.com/assets/1689020/17903032/30b149f0-696a-11e6-9a81-ee1cbb3fb513.jpg)

**Comment by arnorb** [comment]
Vefurinn var upprunalega hannaður með undirstriki á linkunum. Ekki spurning að bæta því við.

**Comment by viktorsmari** [comment]
Snilld, var að commita þessu!
