### ISSUE TITLE
HIGH Priority - Connect respective news categories to aðildarfélög pages

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#37]
This page does not display the news from the Píratar í Hafnarfirði category on this page:
http://piratar.is/hafnarfjordur/

Kópavogur, 
news from the category Píratar í Kópavogi are not published on the Kópavogur page 
http://piratar.is/kopavogur/

Seltjarnarnes,
same problem, connect to Píratar á Seltjarnarnesi category
http://piratar.is/seltjarnarnes/

Suðurnes
same problem, connect to Píratar á Suðurnesjum category
(plus fundargerðir also missing from category Suðurnes)
http://piratar.is/sudurnes/

Vesturland
same problem, connect to Píratar á Vesturlandi category
http://piratar.is/vesturland/

Norðausturland
same problem connect to Píratar á Norðausturlandi category
http://piratar.is/nordausturland/

Vestfirðir
same problem, connect to Píratar á Vestfjörðum category
http://piratar.is/vestfirdir/

Suðurland
same problem, connect to Píratar á Suðurlandi category
http://piratar.is/sudurland/

Austurland
same problem, connect to Píratar á Austurlandi category
http://piratar.is/austurland/

**Comment by thorlaug** [comment]
Here the aðildarfélag page works perfectly http://piratar.is/piratar-60/
(but is missing some content on my end)

**Comment by thorlaug** [comment]
Píratar á Suðurnesjum pulls stjórn from Suðurnes. The page does not publish the laws for Suðurnes either but they are in the Lög Pírata system.

**Comment by baldurjonsson** [comment]
Allt hérna klárt, má endilega loka @thorlaug
