### ISSUE TITLE
Shorten excerpt for Flokksfólk on aðildarfélag page

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#39]
On the aðildarfélag pages the chairperson gets a big image and a teaser text that's pulled from the Flokksfólk system. The preview needs to pull a certain number of characters so the look stays within borders.
Example of an intro that's too long and messes up the look of the aðildarfélag page
http://piratar.is/adildarfelog/sudvesturkjordaemi/

**Comment by thorlaug** [comment]
another example of the too long text intro http://piratar.is/vesturland/

**Comment by viktorsmari** [comment]
@thorlaug Check if this is resolved :dancers:

**Comment by thorlaug** [comment]
Wuuuunderbar!
