### ISSUE TITLE
display numbered lists, add ol look to css

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#42]
numbered bullets <ol> aren't displayed on the web, see laws here for aðildarfélag, list code is fine but front-end look on this page doesn't display any numbers.

http://piratar.is/log-pirata/log-pirata-a-austurlandi/

**Comment by arnorb** [comment]
To clarify: The problem is (or seems to be) that there needs to be a definition for multiple levels of ordered lists. So the first level is fine (the purple headings) but their children are not.

**Comment by andri** [comment]
Fixed indirectly.
