### ISSUE TITLE
Make single item heading text white

### ISSUE THREAD

**Issue by arnorb** [piratar/piratar.is#43]
Það vantar allan contrast sjá t.d. http://piratar.is/frettir/frettir/stadfestingakosning-frambodslista-na-kjordaemis/

**Comment by andri** [comment]
Vorum einmitt að skoða þetta mál. Ég skal taka þetta.

**Comment by viktorsmari** [comment]
Ég lét bakgrunnin vera hvítari, bara svo þetta væri læsilegra.

**Comment by andri** [comment]
Fixed indirectly.
