### ISSUE TITLE
Remove upper case letters in headlines & 'more' linke

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#44]
<img width="374" alt="screen shot 2016-08-26 at 13 26 56" src="https://cloud.githubusercontent.com/assets/5758526/18006626/f1999696-6b8f-11e6-812a-840a2f1e9a00.png">
Remove high-case from CSS for news on frontpage
We don't use High-Case anymore on piratar.i, please remove high-case from the style sheet. See above for news on frontpage.

**Comment by arnorb** [comment]
Fixed in #48

**Comment by arnorb** [comment]
I accidentally put everything in lowercase instead without realizing, was a bit sleepy.

**Comment by viktorsmari** [comment]
Fixed
