### ISSUE TITLE
Header on mobile site

### ISSUE THREAD

**Issue by NoiKristinsson** [piratar/piratar.is#46]
When opening the menu on the frontpage in mobile view the header blocks the top three links.

**Comment by baldurjonsson** [comment]
Also mentioned in #31

**Comment by arnorb** [comment]
This has actually been fixed in source ( see #31 ) but the site hasn't been updated to reflect the changes.

**Comment by viktorsmari** [comment]
Half of the problem should be uploaded now on live server. Renamed the issue to target the second problem.
