### ISSUE TITLE
News page look

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#52]
When news stories are published (news page) the headline is overlaying Einkennismynd on a semi-transparent background. Please make this black background have almost no opacity (be less transparent)

Some images make it currently hard to read the headline, a more solid background should fix that.

example
http://piratar.is/frettir/frettir/frambodslistar-i-rvk-n-rvk-s-og-sudvesturkjordaemi/

**Comment by viktorsmari** [comment]
Duplicate? #43

**Comment by thorlaug** [comment]
yes, same request for readable headlines

---

Þórlaug (Thora) Ágústsdóttir
gsm: +354 6998892
Twitter og skype @thorlaug
