### ISSUE TITLE
Put a calendar icon in front of the calendar header on the front page

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#53]
Please make us a little purple calendar icon to put next to the link to the calendar on frontpage esp for mobile version

**Comment by arnorb** [comment]
@thorlaug Something like this? 

<img width="397" alt="screen shot 2016-08-31 at 20 58 59" src="https://cloud.githubusercontent.com/assets/2539132/18146179/d38a62a2-6fbd-11e6-8e8f-d560c0baca56.png">

**Comment by thorlaug** [comment]
nákvæmlega fucking svona!!!

---

Þórlaug (Thora) Ágústsdóttir
gsm: +354 6998892
Twitter og skype @thorlaug

**Comment by arnorb** [comment]
@viktorsmari getur þú sett þetta inn? Mér sýnist að þetta sé plugin-tengt og þurfi að fara inn innan í wordpress bakendanum. 

`<i class="fa fa-calendar"></i>` (passa að hafa bil fyrir aftan þetta) þyrfti þá að fara fremst í `<h2/>` í Viðburðadagatalinu.

**Comment by viktorsmari** [comment]
Ég leitaði og fann ekki hvar þetta á að fara inn, @thorlaug má ekki græja aðgang fyrir @arnorb ?

**Comment by thorlaug** [comment]
jú það finnst mér - @andri getur þú sett þetta á todolistann (og ef einhverjir fleiri þurfa að fá aðgang núna)
