### ISSUE TITLE
Election page 2016 mockup

### ISSUE THREAD

**Issue by andri** [piratar/piratar.is#55]
Notes from meeting on August 31

Content and features needed:
- Kjördæmi/Frambjóðendur/Listar/Myndir
  - Mynd (Top)
  - Myndband (top 5)
  - Starfstitill
  - Texti
  - Linkur á blogg / kosningasíðu
- Píratar í fjölmiðlum (Grid af fréttum sem birtast í fjölmiðlum)
- Stefnuskrá (verið að leggja drög að)
- Karolina fund banner/linkur
- Hvernig á að kjósa / Kjörstaðir
- Fyrir fjölmiðla (Linkur á fjölmiðlasíðu?)
  - Contacts
  - Lógós / Myndir
  - Kafteins
- Taka þátt / Sjálfboðaliðar tengill.

Tengd mál:
#51

**Comment by andri** [comment]
@thorlaug hérna eru punktarnir sem ég skrifaði í gær. Ég nota þetta til að teikna mockup seinna í dag.

**Comment by andri** [comment]
![img_2181](https://cloud.githubusercontent.com/assets/123914/18172164/e89c23e2-7053-11e6-9ff3-c1295d676e09.JPG)

**Kosniga undirsíða/forsíða**

Stefnumál og áherslur flokksins fyrir kosningar kemur efast. Þetta efni er í vinnslu svo við getum ekki hannað það svæði núna.

Næst koma top 5 frambjóðendur úr öllum kjördæmum og CTA takki til að skoða alla frambjóðendur (undir síða sem listar alla).

Svo kemur svæði með fréttum af pírötum í fjölmiðlum. Tenglar á fréttir á síðum fjölmiðla.

Að lokum eru þrír kassar með tenglum á upplýsingar handa kjósendum, fjölmiðlum og sjálfboðaliðum.

_ATH_ – Fattaði núna að ég gleymdi Karolina Fund bannernum. Hann kæmi þarna fyrir neðan stefnumálin og ofan frambjóðendur með grafrík frá auglýsingastofunni.

**Listi yfir frambjóðendur**

Síða sem listar alla frambjóðendur flokkað eftir kjördæmum. Hver frambjóðndi er svo með link yfir á sína síðu eða profíl.

**Comment by thorlaug** [comment]
Það vantar efst í lýsinguna að viðburðir linkur eða yfirlit þarf að vera með á forsíðu
og fréttir (annað en Píratar í fjölmiðlum)

Þriðji mögulegi fréttaflokkurinn eru greinar frá frambjóðendum annaðhvort inni á síðu kjördæmis eða tengill í greinar/blogg inni á síðu hvers frambjóðanda

**Comment by viktorsmari** [comment]
Það er komið draft að þessari síðu fyrir innskráða hér:
http://piratar.is/kosningar/?page_id=38685&preview=true

**Comment by andri** [comment]
@viktorsmari hvernig stendur þetta issue? Hvað þarf að gera til að koma þessu út?

**Comment by viktorsmari** [comment]
Varðandi myndir af frambjóðendum: 
Ég HELD að þar sem frambjóðandalistinn er settur inn í WYSIWYG editor, þá er auðveldast að gera það sama með myndirnar. Þ.e. afrita myndir af efstu frambjóðendum inní editorinn.

**Comment by viktorsmari** [comment]
By default þá myndi það líta svona út:
![2016-09-12_337x375](https://cloud.githubusercontent.com/assets/1689020/18442985/2d5be810-7913-11e6-8b73-671eebb97856.png)

**Comment by andri** [comment]
@viktorsmari, núna eru þau að taka nýjar myndir fyrir top 5. Væri ekki best að hafa custom field fyrir myndirnar? Það væri amk þægilegast uppá framhaldið.

**Comment by arnorb** [comment]
Hér væri tilvalið að hafa smá margin undir myndinni, þó ekki væri nema 10 eða 20px.
