### ISSUE TITLE
Hugmynd: setja t.d. border á dálkana til að fá meiri contrast?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/piratar.is#56]
Hvað finnst ykkur um að setja einhvern border á dálkana til að þetta skeri sig aðeins meira úr?

![2016-09-02_1215x711](https://cloud.githubusercontent.com/assets/1689020/18217282/45d677ca-715c-11e6-8652-b4fa42732baa.png)

**Comment by viktorsmari** [comment]
Þá helst dálkana sem eru gráir á hvítum bakgrunn. Óþarfi á fjólubláu dálkunum.
![2016-09-02_1282x664](https://cloud.githubusercontent.com/assets/1689020/18217367/a94b50dc-715c-11e6-8f2f-0d042d402433.png)

**Comment by andri** [comment]
Ég myndir frekar taka þessa bordara og bakgrunninn út sko :)

**Comment by arnorb** [comment]
Já sammála Andra. Setja lárétt strik sem separator t.d.

**Comment by viktorsmari** [comment]
Svo þið skiljið betur hvað ég meina, þá er mjög erfitt að sjá á skjánum mínum hvar gráu boxin enda og hvíti bakgrunnurinn byrjar: 
Takið sérstaklega eftir neðri part myndarinnar:

![img_20160903_082753](https://cloud.githubusercontent.com/assets/1689020/18223228/87be84b2-71b0-11e6-93a0-b1abf32f52a7.jpg)

**Comment by thorlaug** [comment]
Looking good!

---

Þórlaug (Thora) Ágústsdóttir
gsm: +354 6998892
Twitter og skype @thorlaug

2016-09-02 20:27 GMT+00:00 Viktor Smári notifications@github.com:
