### ISSUE TITLE
Taka út gula litinn á forsíðu kosningavefs

### ISSUE THREAD

**Issue by arnorb** [piratar/piratar.is#58]
Það er bara alls ekki nógu mikill kontrast, þessi guli má bara nota á dökkum grunni og sparlega, ekki sem svona "burðar" fyrirsagnir. 

Ég sé ekki betur en að þetta sé gert inní WordPress en ég er ekki kominn með aðgang ennþá.

**Comment by andri** [comment]
Fixed indirectly
