### ISSUE TITLE
Láta Arnór fá aðgang inn á WordPress

### ISSUE THREAD

**Issue by arnorb** [piratar/piratar.is#59]

**Comment by andri** [comment]
@arnorb Búinn að bæta þér við. Fékkstu póst?

**Comment by arnorb** [comment]
Ójá!

**Comment by arnorb** [comment]
@andri Ég þarf að fá aukna notendaheimild. Það eina sem ég get gert núna er að setja inn notandaupplýsingarnar mínar.

**Comment by andri** [comment]
@arnorb Ætti að vera komið núna!
