### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by andri** [piratar/piratar.is#6]
Design and create a simple design guide for the site.

**Comment by maranomynet** [comment]
Hönnunarhópur er alveg að verða búinn með þessa vinnu.

**Comment by OlgaCilia** [comment]
nice!

**Comment by arnorb** [comment]
Er eitthvað að frétta af þessu? @hallakol

**Comment by arnorb** [comment]
Ég ræddi þetta aðeins við Höllu í gær og style guide er á leiðinni, vonandi sem fyrst.

**Comment by hallakol** [comment]
Eta 1 1/2 vika _krossar putta_

Kv, 
Halla
771 4321

**Comment by hallakol** [comment]
Styleguide er kominn inn á vef Pírata, hannaður af Arnóri.
