### ISSUE TITLE
Uppfæra templates fyrir síður frambjóðenda

### ISSUE THREAD

**Issue by aerugo** [piratar/piratar.is#63]
Þegar maður googlar nafn frambjóðenda (dæmi: https://www.google.is/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Krist%C3%ADn+Vala+p%C3%ADratar) lendir maður á síðu sem er ekki með template.

**Comment by andri** [comment]
Fixed in branch Kosningar2016
