### ISSUE TITLE
Mynd með einstakri frétt

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#64]
Sjá hvernig einkennismyndin með fréttinni birtist fyrir ofan meginmál:
http://piratar.is/frettir/frettir/raeda-birgittu-jonsdottir-i-eldhusdagsumraedum-althingis/

sleppa henni í meginmáli eða tengja betur efni

Kosningar 2016 #Kosningar2016

**Comment by andri** [comment]
Þessi linkur virkar ekki, ertu með annað dæmi?

**Comment by andri** [comment]
@thorlaug, vantar betri lýsingu á því hvað vandamálið sé.

**Comment by thorlaug** [comment]
þetta var lagað með betri mynd
