### ISSUE TITLE
Forsíðufréttir - archive / eldri fréttir vantar

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#66]
á forsíðuna vantar link undir fréttirnar sem vísar inn á news archive - sem hefur hingað til verið hér:

http://piratar.is/forsida/frettir/

þarna þarf að laga formattið á birtigunni á fréttalista líka
# Kosningar2016 Kosningavefur

**Comment by andri** [comment]
Komið!

**Comment by andri** [comment]
http://piratar.is/frettir/

**Comment by thorlaug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fréttir, archives og tengingar](https://trello.com/c/z6OmOk4v/18-fr%C3%A9ttir-archives-og-tengingar)
