### ISSUE TITLE
Útlit - forsíða, frambjóðendabirting

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#69]
Forsíða, birting á frambjóðendum
skölun
þegar lúkkið skalast og ég minnka gluggann þá stækka myndirnar af frambjóðendum og hoppa í 2 línur, stækkunin á myndunum af frambjóðendunum virkar illa
# kosningar2016

**Comment by andri** [comment]
Þetta er eins og ég hannaði þetta. Þegar plássið minnkar er ekki hægt að vera með 5 nöfn í einni línu. Sérstaklega á mobile. Þetta er í raun bara á ipad sem þetta fer í fleiri línur og svo tveir frambjóðendur í línu á mobile.
