### ISSUE TITLE
Valmynd ef að gluggi er minnkaður og stækkaður

### ISSUE THREAD

**Issue by baldurjonsson** [piratar/piratar.is#70]
Hæhæ,
Ef að glugginn er minnkaður til helminga kemur mobile hamborgarinn, ef smellt er á hann og valmyndinni lokað og gluggi stækkaður aftur hverfur aðal valmyndin.

![image](https://cloud.githubusercontent.com/assets/3398226/19156196/9a0e584c-8bd0-11e6-9660-6d57271acfb6.png)

![image](https://cloud.githubusercontent.com/assets/3398226/19156223/accb3ef0-8bd0-11e6-9732-5118d0d21333.png)

![image](https://cloud.githubusercontent.com/assets/3398226/19156244/be92d1ca-8bd0-11e6-96ab-6ced03efcba0.png)

![image](https://cloud.githubusercontent.com/assets/3398226/19156267/cdda9168-8bd0-11e6-8998-7c0029c694f1.png)

**Comment by andri** [comment]
Takk fyrir þetta. Fixed!
