### ISSUE TITLE
Bókhald er svartur texti á svörtum bakgrunni

### ISSUE THREAD

**Issue by baldurjonsson** [piratar/piratar.is#71]
Hæhæ,
Undir ártölunum í bókhaldinu sést ekkert en textinn er í markupinu, bakgrunnurinn er svartur og textinn er svartur.

http://piratar.is/um-pirata/bokhald-og-rekstur/bokhald/2014/

![image](https://cloud.githubusercontent.com/assets/3398226/19156354/2881ed3c-8bd1-11e6-95bf-2b19258623f5.png)

**Comment by baldurjonsson** [comment]
Heyrðu nei, CSSið er að setja footerinn yfir contentið

**Comment by baldurjonsson** [comment]
Hálflagast með að taka `position: relative` af footernum

![image](https://cloud.githubusercontent.com/assets/3398226/19156526/ba2597e8-8bd1-11e6-8b7b-f468b8988c4b.png)

**Comment by andri** [comment]
Fixed, öll template eru komið með nýjan strúktur og þessi síða var að nota gamla HTMLið. Fixed.
