### ISSUE TITLE
Setja inn meta fyrir facebook o.fl. á undirsíður

### ISSUE THREAD

**Issue by aerugo** [piratar/piratar.is#72]
Það er rangt thumbnail á Facebook.

Dæmi: Þegar http://piratar.is/kosningar/frambjodendur/ er sett á FB.

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fpiratar.is%2Fkosningar%2Fframbjodendur%2F

**Comment by arnorb** [comment]
Spurning um að setja upp metaplugin svo það sé hægt að skilgreina betur hvaða myndir og texta facebook sækir. Yoast SEO heitir eitt, svo var annað sem ég man ekki hvað heitir en ég man ekki hvort er meira notað.

**Comment by BergthorTh** [comment]
meta er skilgreint fyrir aðalsíðuna piratar.is en virðist ekki vera það fyrir undirsíðurnar. Þá virðist hafa orðið eftir kóði frá prófkjörshamnum í undirsíðunum sem skilar sér í undarlegu description ef undirsíður er deilt beint. Sbr. mynd:
![screenshot 2016-10-07 11 26 07](https://cloud.githubusercontent.com/assets/18063578/19188406/03f0f0ca-8c81-11e6-9bd4-b99b9ca4643f.png)

**Comment by andri** [comment]
Búinn að setja upp Yoast plugin og default Open Graph mynd.
