### ISSUE TITLE
Skipta um placeholdermynd þegar vantar mynd af frambjóðanda

### ISSUE THREAD

**Issue by aerugo** [piratar/piratar.is#73]
Þegar vantar mynd af frambjóðenda kemur mynd af ketti. Skiptum út í Píratamerkið.

**Comment by andri** [comment]
Hvað er Píratalegra en sætur köttur??! :)

**Comment by arnorb** [comment]
Ég hef ekki séð þessa kattamynd en myndi leggja til að í staðinn fyrir að vera að stimpla píratamerkinu út um allt sem placeholder að nota frekar hlutlaust avatar-icon eins og fa-user úr fontawesome.

**Comment by andri** [comment]
Fixed
