### ISSUE TITLE
meta tags vantar á undirsíðum

### ISSUE THREAD

**Issue by BergthorTh** [piratar/piratar.is#75]
Meta tags virðast ekki vera skilgreind á undirsíðum heldur bara á forsíðu. Þá virðist hafa orðið eftir kóði frá prófkjörshamnum á undirsíðunum. Það ásamt skorti á meta tags skilar sér í óheppilegu description þegar undirsíðu er deilt beint. Sjá mynd:
![screenshot 2016-10-07 11 26 07](https://cloud.githubusercontent.com/assets/18063578/19188544/e1de1386-8c81-11e6-814a-70695a24bed8.png)

**Comment by arnorb** [comment]
Loka þessu því #72 fjallar um sama vandamál.
