### ISSUE TITLE
Einkennismynd birtist ekki

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#77]
Þessi síða birtir ekki valda einkennismynd
http://piratar.is/piratar-a-thingi/thingflokkur-pirata/ur-raedustol/
# kosningar2016 #vefur2016

**Comment by thorlaug** [comment]
Einkennismynd birtist ekki hér (engir íslenskir stafir í nafni)
http://piratar.is/piratar-a-thingi/thingfolk/

**Comment by thorlaug** [comment]
Sama vandamál hér 

http://piratar.is/piratar-a-thingi/thingfolk/birgitta-jonsdottir/
http://piratar.is/piratar-a-thingi/thingfolk/helgi-hrafn-gunnarsson/
http://piratar.is/piratar-a-thingi/thingfolk/asta-helgadottir/

http://piratar.is/piratar-a-thingi/frettir/

**Comment by andri** [comment]
Ætti að vera komið í lag núna. Notar sama template og fréttir.
