### ISSUE TITLE
Flokksfólk 'síður' birtast ekki. Priority: High

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#80]
Síður sem eiga að birta upplýsingar um fólk í stjórnum úr kerfinu Flokksfólk birtast ekki, sjá hér

http://piratar.is/flokksfolk/vestfirdir/olof-maria-jonsdottir/
# kosningar2016 #vefur2016

Priority: High

**Comment by arnorb** [comment]
Issue #76 er safn af síðum með sama vandamál.

**Comment by andri** [comment]
Fixed
