### ISSUE TITLE
Scaling á mynd af frambjóðanda

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#81]
laga scaling á frambjóðendamyndum, þetta gerist þegar browser glugginn er minnkaður
<img width="1167" alt="screen shot 2016-10-14 at 21 04 55" src="https://cloud.githubusercontent.com/assets/5758526/19402743/4707d7ee-9252-11e6-9309-763df3de8b58.png">

**Comment by thorlaug** [comment]
eðlileg uppsetning til samanburðar
<img width="1195" alt="screen shot 2016-10-14 at 21 09 21" src="https://cloud.githubusercontent.com/assets/5758526/19402772/89d4044e-9252-11e6-8773-2162e7d8a5b1.png">

**Comment by andri** [comment]
Þetta á að vera svona svo að myndirnar og nöfnin passi á minni skjám.

**Comment by thorlaug** [comment]
raðmöguleikinn 4 frambjóðendur kemur aldrei upp í sköluninni þannig að myndirnar með 3 frambjóðendum í röð verða óeðlilega stórar þegar browserglugginn er minnkaður/stækkaður eða paddinum flippað, það er eins og hoppið sé bara á milli 3 eða 5 í röð en 4 í röð lúkkar betur á sumum skjám.
