### ISSUE TITLE
Svartar síður

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#84]
Þessi síða er svört/birtist ekki á vefnum

http://piratar.is/um-pirata/bokhald-og-rekstur/framkvaemdarad/framkvaemdarad-fyrri-ara/

hún er í Fundargerðir fyrri ára templeitinu
# HIGHpriority

**Comment by helgihg** [comment]
Fixed with commit: https://github.com/piratar/piratar.is/commit/554fdde43ed55ebe9315592eed85ab39a6d38156

**Comment by helgihg** [comment]
Re-opening. Found more pages with the same bug: http://piratar.is/fundargerdir/framkvaemdarad/fundur-framkvaemdarads-6-september-2016/

**Comment by helgihg** [comment]
Fixed with commit: https://github.com/piratar/piratar.is/commit/311283b56e86495f5e848c7f17a0f2b40413c201

(Hopefully for good, this time!)
