### ISSUE TITLE
Feature: Groups and member associations

### ISSUE THREAD

**Issue by andri** [piratar/piratar.is#9]
We need to be able to create groups on the site for various purposes.

There are a few main use cases here:
- Member associations (Aðilarfélög) should have their own section on the site, almost like mini-sites within the main site displaying news, meetings etc for the associations.
- Working groups (Málefnahópar) should also have their place where they can organize, post news and information about their meetings and work.
- Unformal groups and teams could also have a page, like the media/PR team or the web team.

Its possible that these groups need a parent/child relationship built in. Associations have working groups for an example. Also, we should consider if the Parliamentary group could not use this same template.

Group features and content:
- Basic information (name, contact information)
- Members (representatives, board, candidates)
- News/blog
- Policies
- Association laws
- Meeting notes
- Events
- Group access control. Some users should only have access to the group they are responsible for.

**Comment by BergthorTh** [comment]
Wouldn't the "multisite" feature be the most efficient and prudent way of achieving this goal. That way admin and editor rights can be better managed. There would be one main site and each chapter would get a childsite. That way each group would be responsible for maintaining their own site with help and guidance from superusers. This would limit the number of people with admin and/or editor rights for the main site.
