### ISSUE TITLE
Innsetning mynda / Myndbirtingar

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#90]
Það vantar möguleika til að birta myndir með myndatexta í cssið - sjá dæmi hér http://piratar.is/um-pirata/bokhald-og-rekstur/bokhald/

sjá hér
<img width="1044" alt="myndatextiasidu" src="https://cloud.githubusercontent.com/assets/5758526/19837376/c4d11f86-9eb0-11e6-8e5d-cbe8e122b70f.png">
<img width="1040" alt="myndatextiieditor" src="https://cloud.githubusercontent.com/assets/5758526/19837375/c4d11022-9eb0-11e6-8575-8ab6fc05f0cf.png">

**Comment by helgihg** [comment]
Fixed with commit 5d30e90348fded437c13249f24183932b69b6bbb.

Note that styles themselves were not changed so that no special styling was added. Such modifications would be for another issue.
