### ISSUE TITLE
Stefnumál Grunnstefna birtist ekki

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#91]
Þessi síða kemur upp á google http://piratar.is/stefnumal/grunnstefna-pirata/

og á að innihalda grunnstefnuna okkar / vísa á samþykkta grunnstefnu á x.piratar.is

En þess í stað birtist ekkert.
Hér þarf að laga stefnumálið þannig að það vísi áfram.

**Comment by thorlaug** [comment]
Sjá hér yfirlit um stefnumál á piratar.is - hver linkur forwardast á x.piratar.is 
http://piratar.is/stefna/stefnumal/
**NB** - linkurinn neðst á grunnstefnuna virkar á þessari síðu.

**Comment by thorlaug** [comment]
Mér skilst að þetta sé að gerast með mörg stefnumál og einfaldast að leysa þetta því bara með því að undanskilja þessar tómu síður með því að breyta robots skjalinu
- eða með því að láta þessar síður vera til sem síður og hafa inni á þeim link inn á stefnumálin á x.piratar.is. Second og third opinion appreciated!

**Comment by helgihg** [comment]
Með hliðsjón af umfjöllun: http://smepals.com/google-panda/when-use-robots-txt-301-redirects-panda-seo-recovery

Ég bætti við svokallaðari 301-áframsendingu (sjá grein að ofan) í .htaccess skrána þannig að gamla slóðin endurkastar bæði notanda og leitarvélum á nýju slóðina. Komment fylgir .htaccess-línunni um að fjarlægja hana þegar leitarvélar hafa uppfært sína slóð og þegar 9. janúar 2016 er orðið fyrir löngu síðan.

Ég opnaði einnig nýtt verk varðandi stefnumálin sem ekki eru grunnstefnan. Vandamálið við stefnumálin þarf að leysa öðruvísi.

**Comment by helgihg** [comment]
Með hliðsjón af umfjöllun: http://smepals.com/google-panda/when-use-robots-txt-301-redirects-panda-seo-recovery

Ég bætti við svokallaðari 301-áframsendingu (sjá grein að ofan) í .htaccess skrána þannig að gamla slóðin endurkastar bæði notanda og leitarvélum á nýju slóðina. Komment fylgir .htaccess-línunni um að fjarlægja hana þegar leitarvélar hafa uppfært sína slóð og þegar 9. janúar 2016 er orðið fyrir löngu síðan.

Ég opnaði einnig nýtt verk varðandi stefnumálin sem ekki eru grunnstefnan. Vandamálið við stefnumálin þarf að leysa öðruvísi.
