### ISSUE TITLE
Stefnumál Reykjavíkur

### ISSUE THREAD

**Issue by NoiKristinsson** [piratar/piratar.is#92]
Stefnumál Reykjavíkurborgar er ekki lengur til á vefsíðunni, né stefnu mál nokkurra sveitastjórna.
Þetta var áður til líkt og má sjá hér og engin sýnileg leið til að bæta þessu við:
https://web.archive.org/web/20160421054151/http://www.piratar.is/sveitarstjorn/reykjavik/stefnumal/

**Comment by thorlaug** [comment]
Content issue, ekki forritunarvilla. Það er hægt að leysa þetta af fólki í webeditors hónum með því að búa til síðu. Get aðstoðað þig við þetta ef þarf.

Uppfært: í vinnslu hér http://piratar.is/adildarfelogin/stefnumal-pirata-reykjavik/
