### ISSUE TITLE
Neyða síðu til að vera alltaf yfir HTTPS

### ISSUE THREAD

**Issue by helgihg** [piratar/piratar.is#94]
Samkvæmt frétt:
http://www.techtimes.com/articles/12631/20140811/google-favors-encryption-https-sites-to-get-search-ranking-boost.htm

Google mun meta síður meira sem eru yfir HTTPS. Við erum ennfremur með virkt HTTPS nú þegar og það er engin góð ástæða fyrir því að leyfa HTTP umferð yfirhöfuð.

**Comment by thorlaug** [comment]
#MediumPriority

**Comment by baldurjonsson** [comment]
Það er hak í WP admin einhversstaðar sem breytir öllum linkum sem eru búin til með föllum í templeitum í https. Það redirectar líka allar beinar heimsóknir á http.
En það leysir ekki allar tilvísanir í myndir og aðra fæla sem eru í gagnagrunninum nú þegar. Það þyrfti að finna eða skrifa eitthvað fallegt sem uppfærir alla posts í gagnagrunninum.

**Comment by baldurjonsson** [comment]
Hæhæ,
Ég legg til að þetta verði High Priority. Bæði v/ greinarinnar sem @helgihg linkar í en einnig er smá umfjöllun um þetta þessa dagana í nördahópum.

Mér sýnist síðan öll virka í https, getum við ekki byrjað á redirectinu, og ef eitthvað verður unsecure v/ eitthvað loadast yfir https lagað það í rólegheitunum?

@thorlaug 

https://www.lappari.com/2017/02/ooruggir-vefir-lifeyrissjoda-stjornmalaflokka-og-ymisa-fyrirtaekja/

**Comment by thorlaug** [comment]
Björn Thor virkjaði þetta fyrir okkur.
